
resources:
  repositories:
  - repository: 'JenkinsSdkSetupScripts'
    type: github
    endpoint: 'GitHub connection MockVMAgent'
    name: PlayFab/JenkinsSdkSetupScripts
    path: .
    trigger:
      - master
  - repository: API_Specs
    type: github
    endpoint: 'GitHub connection MockVMAgent'
    name: PlayFab/API_Specs
    path: ./API_Specs
    trigger:
      - master
  - repository: CSharpSDK
    type: github
    endpoint: 'GitHub connection MockVMAgent'
    name: PlayFab/CSharpSDK
    path: ./sdks/
    trigger:
      - master

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: true
  persistCredentials: true
  path: s/SDKGenerator

- task: PowerShell@2
  displayName: "Create folders for repos (workaround)"
  inputs:
    targetType: inline
    script: |
        cd ..
        New-Item -Path . -Name "SDKGenerator" -ItemType "directory" # Equals "self"
        New-Item -Path . -Name "JenkinsSdkSetupScripts" -ItemType "directory" # Equals "self"
        New-Item -Path . -Name "API_Specs" -ItemType "directory" # Equals "self"
        New-Item -Path . -Name "sdks" -ItemType "directory" # Equals "self"
        cd sdks
        New-Item -Path . -Name "CSharpSDK" -ItemType "directory" # Equals "self"
    pwsh: true

- checkout: API_Specs
  clean: true
  persistCredentials: true
  path: s/API_Specs

- checkout: JenkinsSdkSetupScripts
  clean: true
  persistCredentials: true
  path: s/JenkinsSdkSetupScripts

- checkout: CSharpSDK
  clean: true
  persistCredentials: true
  path: s/sdks/CSharpSDK

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    cd ..
    pwd
    ls
  displayName: 'Cloning CSharpSDK for genConfig'

- script: |
    ls
    cd s
    cd SDKGenerator/SDKBuildScripts/Windows
    ./csharp_build.bat
  displayName: 'Generating CSharpSDK'

- task: UseDotNet@2
  displayName: 'Use .NET Core 2.x sdk'
  inputs:
    packageType: sdk
    version: 2.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

# - script: |
#     echo SANITY CHECK FOR PREVIOUS DOT NET CHANGE
#     dotnet --list-sdks
#   displayName: 'looking for dot net version'

- task: NuGetCommand@2
  displayName: 'Nuget Restore CSharpSDK UnitTest'
  inputs:
    command: 'restore'
    restoreSolution: 'sdks/CSharpSDK/PlayFabSDK/PlayFabSDK+Unit.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Build CSharpSDKUnitTest: Release'
  inputs:
    solution: 'sdks/CSharpSDK/PlayFabSDK/PlayFabSDK+Unit.sln'
    configuration: 'Release'
    clean: true
    msbuildArchitecture: 'x64'

# - script: |
#     cd sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/
#     echo START UNIT TEST RUNNER
#     setx PF_TEST_TITLE_DATA_JSON 'D:\a\1\s\JenkinsSdkSetupScripts\JenkinsSdkSetupScripts\Creds\testTitleData.json'
#     cp 'D:\a\1\s\JenkinsSdkSetupScripts\JenkinsSdkSetupScripts\Creds\testTitleData.json' D:\a\1\s\sdks\CSharpSDK\PlayFabSDK\UnittestRunner\bin\Release\netcoreapp2.0\testTilteData.json
#     dotnet .\UnitTestRunner.dll -testInputsFile testTitleData.json
#   displayName: 'NetCore 2.0 CSharpSDK UnitTestRunner'

- script: |
    cd sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/net45/
    echo START UNIT TEST RUNNER
    setx PF_TEST_TITLE_DATA_JSON 'D:\a\1\s\JenkinsSdkSetupScripts\JenkinsSdkSetupScripts\Creds\testTitleData.json'
    cp 'D:\a\1\s\JenkinsSdkSetupScripts\JenkinsSdkSetupScripts\Creds\testTitleData.json' D:\a\1\s\sdks\CSharpSDK\PlayFabSDK\UnittestRunner\bin\Release\net45\testTilteData.json
    .\UnitTestRunner.exe -testInputsFile testTitleData.json
  displayName: 'dotNet 45 CSharpSDK UnitTestRunner'

# - task: DotNetCoreCLI@2
#   displayName: 'CSharpSDK UnitTest Run'
#   inputs:
#     command: 'run'
#     projects: '../sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/UnittestRunner.dll'
#     arguments: '-o ../sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/ -testInputsFile SYNCJENKINSADDTESTTITLEDATAJSON'
#     modifyOutputPath: true

