# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    pwd
    ls
    cd ..
    mkdir "sdks"
    pushd "sdks"
    git clone https://github.com/PlayFab/CSharpSDK.git
    popd
  displayName: 'Cloning CSharpSDK'

- script: |
    ls
    cd s
    cd SDKBuildScripts/Windows
    ./csharp_build.bat
  displayName: 'generating CSharpSDK'
 
- script: |
    cd ../sdks/CSharpSDK/PlayFabSDK/
    pwd
    ls
  displayName: 'testing csharp'

- task: UseDotNet@2
  displayName: 'Use .NET Core 2.x sdk'
  inputs:
    packageType: sdk
    version: 2.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    echo ALL THE DOT NET SDKs
    dotnet --list-sdks
  displayName: 'looking for dot net version'

- task: NuGetCommand@2
  displayName: 'Nuget Restore CSharpSDK UnitTest'
  inputs:
    command: 'restore'
    restoreSolution: '../sdks/CSharpSDK/PlayFabSDK/PlayFabSDK+Unit.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Build CSharpSDKUnitTest: Release'
  inputs:
    solution: '../sdks/CSharpSDK/PlayFabSDK/PlayFabSDK+Unit.sln'
    configuration: 'Release'
    clean: true
    msbuildArchitecture: 'x64'

# TODO: this technically should work. But we don't have a release, maybe that's inappropriate though for a private repo.
# - task: DownloadGitHubRelease@0
#   inputs:
#     connection: 'GitHub connection MockVMAgent'
#     userRepository: 'PlayFab/JenkinsSdkSetupScripts'
#     defaultVersionType: 'latest'
#     downloadPath: '$(System.ArtifactsDirectory)'

- script: |
    git clone https://github.com/PlayFab/JenkinsSdkSetupScripts.git
    cd ../sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/
    dotnet .\UnitTestRunner.dll -testInputsFile '$(System.ArtifactsDirectory)'/JenkinsSdkSetupScripts/JenkinsSdkSetupScripts/Creds/testTitleData.json
  displayName: 'test dot net run script'

# - task: DotNetCoreCLI@2
#   displayName: 'CSharpSDK UnitTest Run'
#   inputs:
#     command: 'run'
#     projects: '../sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/UnittestRunner.dll'
#     arguments: '-o ../sdks/CSharpSDK/PlayFabSDK/UnittestRunner/bin/Release/netcoreapp2.0/ -testInputsFile SYNCJENKINSADDTESTTITLEDATAJSON'
#     modifyOutputPath: true

